apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  selector:
    app: ftps
  ports:
    - name : http
      protocol: TCP
      port: 21
      targetPort: 21
  type: LoadBalancer
