apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name : mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name : ssh
      protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP
